spring.application.name=releasepilot-lite

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/releasepilot}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:releasepilot}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:releasepilot}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:false}

releasepilot.integrations.ingestion-token=${RELEASEPILOT_INGESTION_TOKEN:local-dev-token}
