CREATE TABLE deployments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name VARCHAR(255) NOT NULL,
    version VARCHAR(255) NOT NULL,
    environment VARCHAR(255) NOT NULL DEFAULT 'DEV',
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    CONSTRAINT uk_deployment_service_version UNIQUE (service_name, version, environment)
);

CREATE INDEX idx_deployments_status ON deployments (status);
CREATE INDEX idx_deployments_environment ON deployments (environment);

CREATE TABLE deployment_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deployment_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    message VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    provider VARCHAR(255),
    external_deployment_id VARCHAR(255),
    commit_sha VARCHAR(255),
    branch_name VARCHAR(255),
    triggered_by VARCHAR(255),
    deployment_url VARCHAR(255),
    CONSTRAINT fk_deployment_events_deployment
        FOREIGN KEY (deployment_id)
        REFERENCES deployments (id),
    CONSTRAINT uk_deployment_event_external
        UNIQUE (provider, external_deployment_id, status)
);

CREATE INDEX idx_deployment_events_deployment_id ON deployment_events (deployment_id);
CREATE INDEX idx_deployment_events_occurred_at ON deployment_events (occurred_at);
